import { motion } from "framer-motion";

const GuaranteeSection = () => {
  return (
    <section className="py-32 px-6 lg:px-12 relative">
      <div className="absolute inset-0 bg-card" />
      
      <div className="relative max-w-4xl mx-auto text-center">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <span className="font-mono text-xs tracking-[0.3em] uppercase text-primary mb-8 block">
            Profit Insurance
          </span>
          
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-serif font-bold leading-tight mb-8">
            If it doesn't pay for itself,
            <br />
            <span className="italic text-gradient-gold">you don't pay at all.</span>
          </h2>

          <div className="max-w-2xl mx-auto">
            <p className="text-lg text-secondary-foreground leading-relaxed mb-8">
              Deploy the VSL. Run your ads. Track your numbers.
              If the sales generated by this video don't cover the €1650 investment, 
              you get a full refund. Every cent. No forms to fill. No hoops.
            </p>
            
            <p className="text-foreground font-medium mb-12">
              We carry the risk because we've done this enough times to know the outcome.
            </p>
          </div>

          <div className="inline-block border border-primary/30 px-8 py-4">
            <span className="font-mono text-sm text-primary tracking-wider">
              100% MONEY BACK — PERFORMANCE GUARANTEED
            </span>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default GuaranteeSection;
